### ISSUE TITLE
Small CSS issue on Linux/Chromium

### ISSUE THREAD

**Issue by grubersjoe** [Zren/zren.github.io#1]
Hey there,

I stumpled on a small visual issue on your page. Seems like an unexpected overflow is triggered:

![image](https://user-images.githubusercontent.com/3109364/51045310-95f24780-15c3-11e9-8dbc-79f50c37b84b.png)

This happens in Chromium 71 under Arch Linux (KDE). Firefox works as expected. Google Chrome on a Mac also doesn't have this problem.

**Comment by Zren** [comment]
Thanks for reporting this. I have `overflow-x: none;` set, but I also have `white-space: nowrap;` and `text-overflow: ellipsis;` set so there shouldn't be a y overflow. Maybe the font is larger that the line height for some reason? Weird.

I'm using chromium in Manjaro: `Version 71.0.3578.98 (Official Build) Arch Linux (64-bit)`

![2019-01-11___16-21-56](https://user-images.githubusercontent.com/416367/51060513-fbdbd080-15bd-11e9-840f-8da2edd23d30.png)

I need to rewrite the sidebar menu for mobile anyways, so maybe this'll drive me to actually fix that.

**Comment by grubersjoe** [comment]
I think it is related to the internals of `overflow`. It seems like setting only one axis of overflow like `overflow-x: hidden` leads to an implicit `overflow-y: auto`, which in turn leads to an `overflow-y: scroll` in some browsers. At least that's how I interpret the following:

https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue

I guess you could simply set `overflow: hidden` and it should work as expected then. At least tested in the dev tools, it works then here.
