### ISSUE TITLE
Location of Dolphin Executable in Build Instructions

### ISSUE THREAD

**Issue by gleporeNARA** [Zren/zren.github.io#13]
The build instructions for Dolphin at:

https://zren.github.io/2018/04/30/compiling-dolphin

state: 

You can test if everything went well by running:
./src/dolphin

However, when I follow the instructions, the executable is at /dolphin/build/bin

Which would also change the subsequent move statement: sudo cp ./src/dolphin /usr/local/bin/dolphin

**Comment by Zren** [comment]
Thanks for pointing that out, updated the blog post.
