### ISSUE TITLE
Workout Timer

### ISSUE THREAD

**Issue by digitalethics** [Zren/zren.github.io#6]
Do you still work on the [Workout Timer](https://zren.github.io/2017/07/28/workout-timer) project you mentioned on your website?

**Comment by Zren** [comment]
The workouttimer was a fork of [systraytimer](
https://github.com/Zren/plasma-applet-systraytimer). I never released it as it used Google's TextToSpeech MP3s, and didn't bother cleaning up the code. I don't use or work on that widget.

**Comment by digitalethics** [comment]
Thanks for the quick feedback. It was an interesting project.
