### ISSUE TITLE
Krunner with Meta key, Ubuntu 20.04

### ISSUE THREAD

**Issue by okelet** [Zren/zren.github.io#7]
This combination doesn't work to launch krunner with the Meta key:

```bash
kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.kglobalaccel,/component/krunner,org.kde.kglobalaccel.Component,invokeShortcut,run command"
```

This one does work:

```bash
kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.krunner,/App,,display"
```

**Comment by Zren** [comment]
Oh right, I remember it changed to `/component/krunner_desktop` and `_launch`. It no longer has a "toggle" dbus command, which sucks. It uses a new "API" that will launch the app if if it's not already loaded I think. It's annoying as the first time you run krunner now, it's slow...

```
qdbus org.kde.kglobalaccel /component/krunner_desktop invokeShortcut _launch
```
